Sprint 7 solution in file manager
natalaly/java-kanban pull request #2
Opened 2024-05-12 22:04 UTC by natalaly

2024-05-13 12:12 UTC, kalitva requested changes

2024-05-13 12:12 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/model/Epic.java
> +  public Epic clone() {
Не очень понимаю зачем может понадобиться клонирование..

2024-05-13 12:12 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/model/Task.java
> +public class Task implements Cloneable {
`Cloneable` использовать не очень рекомендуется. Например, почитай это:

https://stackoverflow.com/questions/4081858/how-does-cloneable-work-in-java-and-how-do-i-use-it

2024-05-13 12:12 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/model/TaskType.java
> +  public static TaskType getType(Task task) {
Не очень решение. Определи в `Task` метод 
```java
public TaskType getType() {
    return TaskType.TASK;
}
````

В наследниках переопределишь, возвращая соответствующие типы задач

2024-05-13 12:12 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/model/TaskType.java
> +    } catch (NullPointerException e) {
И npe мы никогда не перехватываем. Если он вылетел, где-то ошибка

2024-05-13 12:12 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/service/FileBackedTaskManager.java
> +  private static final String TASKS_HEADER = "id,type,name,status,description,epic";
Лучше `TASKS_CSV_HEADER` или `CSV_HEADER`

2024-05-13 12:12 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/service/FileBackedTaskManager.java
> +  private String taskToCsvString(final Task task) {
Здесь уместнее использовать полиморфизм - определи метод `toCsvLine` в `Task`, переоепредели в наследниках, если необходимо, и затем вызывай как `task.toCsvline()`

2024-05-13 12:12 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/service/FileBackedTaskManager.java
> +    final String formatReg = "^([^,\"']+,){5}[^,\"']+$";
Вынеси регулярку в константу и назови, чтобы было понятно, что она делает (при необходимости, можно добавить коммент)

2024-05-14 01:42 UTC, natalaly commented on src/ru/yandex/practicum/tasktracker/model/Epic.java
> +  public Epic clone() {
Во время тестирования функции добавления задачи в таск менеджер, я столкнулась с ситуацией когда при добавлении одной и той же задачи три раза - она успешно сохранялась, но id у них были одинаковые(последнее значение), чтоб  обезопаситься от  нежелательных модификаций внутри менеджера при внешних изменений, решила использовать глубокое копирование

2024-05-14 01:42 UTC, natalaly commented on src/ru/yandex/practicum/tasktracker/model/Task.java
> +public class Task implements Cloneable {
спасибо большое! Заинтересовалась SerializationUtils, намерена изучить использования этого тула) Пока не уверена как добавить эту библиотеку в проект, потому на данный момент использовала copy constructor

2024-05-15 12:14 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/model/Epic.java
> +  public Epic clone() {
Разве может в хэшмап сохранится несколько задач? Или я не так понимаю? Про какой тип задач идет речь?

2024-05-15 12:28 UTC, kalitva approved these changes

2024-05-15 12:28 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/model/Subtask.java
> +    return super.toCsvLine().trim() + getEpicId() + System.lineSeparator();
Отлично, но лучше без разделителя в конце

2024-05-15 12:28 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/service/FileBackedTaskManager.java
> +      }
```java
Stream.concat(tasks, epics, subtasks)
    .forEach(t -> fw.write(t.toCsvLine())
```

Можешь объединить три цикла в один стрим
https://www.baeldung.com/java-combine-multiple-collections#using-java-8-stream-api

2024-05-15 12:28 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/service/FileBackedTaskManager.java
> +  private Task fromString(final String stringCSV) {
`stringCSV --> stringCsv` Аббревиатуры тоже в camel case, например не `HTTPRequest`, а `HttpRequest`

https://google.github.io/styleguide/javaguide.html#s5.3-camel-case

2024-05-15 12:28 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/service/FileBackedTaskManager.java
> +    return null;
Нули не следует возвращать (только если по другому никак), давай выбросим здесь исключение, так как это явно ошибка, если исполнение оказалось здесь

2024-05-15 12:29 UTC, kalitva commented on src/ru/yandex/practicum/tasktracker/model/Task.java
> +public class Task implements Cloneable {
Да, обычно используют что-то подобное. Думаю, если уже действительно надо копировать таски, лучше использовать не конструктор, а метод, как было до этого. Просто не через `Cloneable`

2024-05-17 21:06 UTC, natalaly commented on src/ru/yandex/practicum/tasktracker/model/Epic.java
> +  public Epic clone() {
Добавила тест на этот сценарий

2024-05-17 21:21 UTC, merged